routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['set_locale'])->group(function () {
    Route::get('/', 'App\Http\Controllers\IndexController@index');

    Route::get('/project', 'App\Http\Controllers\IndexController@project')->name('project');

    Route::get('/search', 'App\Http\Controllers\IndexController@search')->name('search');
    Route::get('/search/class', 'App\Http\Controllers\IndexController@search_class')->name('search_by_class');

    Route::get('/subjects/{sub}/{class}', 'App\Http\Controllers\ThemeController@index')->name('themes'); //Output themes on frontend
    Route::get('/subjects/{sub}/', 'App\Http\Controllers\ThemeController@category')->name('category'); //Output themes on frontend

    Route::get('/theme/{class}/{theme_id}/', 'App\Http\Controllers\CatalogController@index')->name('catalog'); //Output posts on frontend
    Route::get('/theme/{class}/{theme_id}/{video_id}', 'App\Http\Controllers\CatalogController@theme_video')->name('video'); //Separate video

//Lang routs
    Route::get('/lang/{lang}', 'App\Http\Controllers\IndexController@changeLocale')->name('changeLang');

    Auth::routes();

    Route::redirect('/home', 'admin_panel/');
});

Route::middleware(['role:admin'])->prefix('admin_panel')->group(function () {
    //Routs for admin
    Route::get('/', 'App\Http\Controllers\Admin\HomeController@index')->name('homeAdmin');

    Route::get('getThemes/{cat_id}', [\App\Http\Controllers\Admin\ThemeController::class, 'getThemes'])->name('getThemes');

    Route::resource('category', \App\Http\Controllers\Admin\CategoryController::class);
    Route::resource('post', \App\Http\Controllers\Admin\PostController::class);
    Route::resource('group', \App\Http\Controllers\Admin\GroupController::class); //Class
    Route::resource('theme', \App\Http\Controllers\Admin\ThemeController::class);
    Route::resource('report', \App\Http\Controllers\Admin\ReportController::class);

    Route::get('/content/header', 'App\Http\Controllers\Admin\Content\HeaderController@header_index')->name('header_index');
    Route::post('/content/header/update', 'App\Http\Controllers\Admin\Content\HeaderController@header_update')->name('header_update');

    Route::get('/admin_panel/docs', function () {
        return view('admin.docs.index');
    })->name('docs');

    Route::get('/video/search/index', [\App\Http\Controllers\IndexController::class, 'VideoSearchIndex'])->name('videoSearhIndex');
    Route::get('/video/search/', [\App\Http\Controllers\IndexController::class, 'VideoSearch'])->name('videoSearh');
    Route::get('/theme/search/by/', [\App\Http\Controllers\IndexController::class, 'themeSearch'])->name('searching_by_theme');
    Route::get('/theme/search/index', [\App\Http\Controllers\IndexController::class, 'themeSearchIndex'])->name('themeSearchIndex');


});

Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('view:clear');
    return 'DONE'; //Return anything
});

Route::get("/storage-link", function () {
    Artisan::call('storage:link', []);
});

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/GroupController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Group;
use Illuminate\Http\Request;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = Group::orderBy('created_at', 'DESC')->get();
        return view('admin.group.index', [
            'groups' => $groups
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.group.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $group = new Group();
        $group->number = $request->number;
        $group->save();

        //return redirect()->back()->withSuccess('Класс успешно добавлен!');
		return redirect()->route('group.edit', $group->id)->withSuccess('Класс успешно добавлен!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function show(Group $group)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function edit(Group $group)
    {
        return view('admin.group.edit',[
            'group' => $group
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Group $group)
    {
        $group->number = $request->number;
        $group->save();
        return redirect()->back()->withSuccess('Класс обновлен!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function destroy(Group $group)
    {
        $group->delete();
        return redirect()->back()->withSuccess('Класс успешно удален!');
    }
}

resources/views/admin/group/create.blade.php
@extends('layouts.admin_layout')
@section('title_page', 'Добавить класс')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Добавить класс</h1>
                </div><!-- /.col -->

            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card card-primary">

                @if(session('success'))
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                        <h4><i class="icon fa fa-check"></i>{{session('success')}}</h4>
                    </div>
            @endif

            <!-- /.card-header -->
                <!-- form start -->
                <form action="{{route('group.store')}}" method="POST">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Номер</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" name="number" placeholder="Введите номер класса" required>
                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Добавить</button>
                        </div>
                </form>
            </div>
        </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/group/edit.blade.php
@extends('layouts.admin_layout')
@section('title_page', 'Редактировать класс')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Редактировать класс</h1>
                </div><!-- /.col -->

            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card card-primary">

                @if(session('success'))
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                        <h4><i class="icon fa fa-check"></i>{{session('success')}}</h4>
                    </div>
            @endif

            <!-- /.card-header -->
                <!-- form start -->
                <form action="{{route('group.update', $group->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Номер</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" value="{{$group->number}}" name="number" placeholder="Введите номер класса" required>
                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Добавить</button>
                        </div>
                </form>
            </div>
        </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/group/index.blade.php
@extends('layouts.admin_layout')
@section('title_page', 'Список классов')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Список классов</h1>
                </div><!-- /.col -->

            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                @if(session('success'))
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                        <h4><i class="icon fa fa-check"></i>{{session('success')}}</h4>
                    </div>
                @endif


                <div class="card-body p-0">
                    <table class="table table-striped projects">
                        <thead>
                        <tr>
                            <th style="width: 1%">
                                Id
                            </th>
                            <th style="width: 20%">
                                Номер класса
                            </th>


                            <th style="width: 20%">
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($groups as $group)
                            <tr>
                                <td>
                                    {{$group->id}}
                                </td>
                                <td>
                                    {{$group->number}}
                                </td>

                                <td class="project-actions text-right">
                                    <a class="btn btn-info btn-sm" href="{{route('group.edit', $group->id)}}">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Изменить
                                    </a>
                                    <form action="{{route('group.destroy', $group->id) }}" class="btn" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm delete-btn" href="#">
                                            <i class="fas fa-trash">
                                            </i>
                                            Удалить
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach

                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection