routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['set_locale'])->group(function () {
    Route::get('/', 'App\Http\Controllers\IndexController@index');

    Route::get('/project', 'App\Http\Controllers\IndexController@project')->name('project');

    Route::get('/search', 'App\Http\Controllers\IndexController@search')->name('search');
    Route::get('/search/class', 'App\Http\Controllers\IndexController@search_class')->name('search_by_class');

    Route::get('/subjects/{sub}/{class}', 'App\Http\Controllers\ThemeController@index')->name('themes'); //Output themes on frontend
    Route::get('/subjects/{sub}/', 'App\Http\Controllers\ThemeController@category')->name('category'); //Output themes on frontend

    Route::get('/theme/{class}/{theme_id}/', 'App\Http\Controllers\CatalogController@index')->name('catalog'); //Output posts on frontend
    Route::get('/theme/{class}/{theme_id}/{video_id}', 'App\Http\Controllers\CatalogController@theme_video')->name('video'); //Separate video

//Lang routs
    Route::get('/lang/{lang}', 'App\Http\Controllers\IndexController@changeLocale')->name('changeLang');

    Auth::routes();

    Route::redirect('/home', 'admin_panel/');
});

Route::middleware(['role:admin'])->prefix('admin_panel')->group(function () {
    //Routs for admin
    Route::get('/', 'App\Http\Controllers\Admin\HomeController@index')->name('homeAdmin');

    Route::get('getThemes/{cat_id}', [\App\Http\Controllers\Admin\ThemeController::class, 'getThemes'])->name('getThemes');

    Route::resource('category', \App\Http\Controllers\Admin\CategoryController::class);
    Route::resource('post', \App\Http\Controllers\Admin\PostController::class);
    Route::resource('group', \App\Http\Controllers\Admin\GroupController::class); //Class
    Route::resource('theme', \App\Http\Controllers\Admin\ThemeController::class);
    Route::resource('report', \App\Http\Controllers\Admin\ReportController::class);

    Route::get('/content/header', 'App\Http\Controllers\Admin\Content\HeaderController@header_index')->name('header_index');
    Route::post('/content/header/update', 'App\Http\Controllers\Admin\Content\HeaderController@header_update')->name('header_update');

    Route::get('/admin_panel/docs', function () {
        return view('admin.docs.index');
    })->name('docs');

    Route::get('/video/search/index', [\App\Http\Controllers\IndexController::class, 'VideoSearchIndex'])->name('videoSearhIndex');
    Route::get('/video/search/', [\App\Http\Controllers\IndexController::class, 'VideoSearch'])->name('videoSearh');
    Route::get('/theme/search/by/', [\App\Http\Controllers\IndexController::class, 'themeSearch'])->name('searching_by_theme');
    Route::get('/theme/search/index', [\App\Http\Controllers\IndexController::class, 'themeSearchIndex'])->name('themeSearchIndex');


});

Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('view:clear');
    return 'DONE'; //Return anything
});

Route::get("/storage-link", function () {
    Artisan::call('storage:link', []);
});

app/Models/Report.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'file'
    ];
}

app/Http/Controllers/Admin/ReportController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Report;
use App\Models\WebHostingDoc;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ReportController extends Controller
{

    public function index()
    {
        $reports = Report::all();
        return view('admin.report.index', ['reports' => $reports]);
    }


    public function create()
    {
        return view('admin.report.create');
    }

    public function store(Request $request)
    {
        $data = $request->all();
        try {
            DB::beginTransaction();
            $path = '';
            if (isset($data['file'])) {
                if ($request->hasFile('file')) {
                    $file = $request->file('file');
                    $name = time() . '.' . $file->getClientOriginalExtension();
                    $destinationPath = storage_path('/app/public/reports/');
                    $file->move($destinationPath, $name);
                    $path = '/reports/' . $name;

                }
            }
            $data['file'] = $path;
            Report::create($data);
            DB::commit();
            return redirect(route('report.index'))->withSuccess('Отчет успешно добавлен!');
        } catch (\Exception $exception) {
            DB::rollBack();
            dd($exception->getMessage());
//            return redirect(route('report.index'));
        }
    }


    public function edit(Report $report)
    {
        return view('admin.report.edit', ['report' => $report]);
    }


    public function update(Request $request, Report $report)
    {
        $data = $request->except(['_token', '_method']);
        try {
            DB::beginTransaction();
            $path = null;
            if (isset($data['file'])) {
                if ($request->hasFile('file')) {
                    $file = $request->file('file');
                    $name = time() . '.' . $file->getClientOriginalExtension();
                    $destinationPath = storage_path('/app/public/reports/');
                    $file->move($destinationPath, $name);
                    $path = '/reports/' . $name;

                }
            }
            if ($path) {
                $data['file'] = $path;
            }

            $report->update($data);
            DB::commit();
            return redirect(route('report.index'))->withSuccess('Отчет успешно добавлен!');
        } catch (\Exception $exception) {
            DB::rollBack();
            return [
                'success' => false,
                'message' => $exception->getMessage()
            ];
        }
    }

    public function destroy(Report $report)
    {
        $report->delete();
        return redirect()->back()->withSuccess('Отчет успешно удалена!');
    }
}

resources/views/admin/report/create.blade.php
@extends('layouts.admin_layout')
@section('title_page', 'Добавить отчет')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Добавить отчет</h1>
                </div><!-- /.col -->

            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <div class="card">
        <div class="card-header">
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="alert alert-danger">{{$error}}</div>
                @endforeach
            @endif
        </div>
        <div class="card-body">
            <form action="{{route('report.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Заголовок</label>
                            <input name="title" type="text" class="form-control" placeholder="Заголовок">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="customFile">Выберите файл</label>
                            <div class="custom-file">
                                <input name="file" type="file" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">Выберите файл</label>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/report/edit.blade.php
@extends('layouts.admin_layout')
@section('title_page', 'Редактировать отчет')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Редактировать отчет</h1>
                </div><!-- /.col -->

            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <div class="card">
        <div class="card-body">
            <form action="{{route('report.update', $report)}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Заголовок</label>
                            <input value="{{$report->title}}" name="title" type="text" class="form-control"
                                   placeholder="Заголовок">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="customFile">  Текущий файл: <a href="{{asset('storage' . $report->file)}}" download>
                                    {{$report->file}}
                                </a></label>
                            <div class="custom-file">
                                <input  name="file" type="file" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">
                                    Выберите файл
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/report/index.blade.php
@extends('layouts.admin_layout')
@section('title_page', 'Отчеты')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Все отчеты</h1>
                </div><!-- /.col -->

            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <div class="card">
        <div class="card-header">
            <div class="div">
                <a href="{{route('report.create')}}" class="btn btn-success">
                    Добавить отчет
                </a>
            </div>
        </div>
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Заголовок</th>
                    <th>Файл</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>

                @foreach($reports as $item)
                    <tr>
                        <td>{{$item->title}}</td>
                        <td>
                            <a href="{{asset('storage'.$item->file)}}" download>
                                {{$item->title}}
                            </a>
                        </td>
                        <td>
                            <div class="row">
                                <a href="{{route('report.edit', $item)}}"
                                   class="btn btn-sm btn-primary">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <form action="{{route('report.destroy', $item->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="ml-2 btn btn-sm btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop


@section('plugins.Datatables', true)
@section('js')
    <script src="{{asset("vendor/datatables/js/jquery.dataTables.min.js")}}"></script>
    <script src="{{asset("vendor/datatables/js/dataTables.bootstrap4.min.js")}}"></script>
    <script src="{{asset("vendor/datatables-plugins/responsive/js/dataTables.responsive.min.js")}}"></script>
    <script src="{{asset("vendor/datatables-plugins/responsive/js/responsive.bootstrap4.min.js")}}"></script>
    <script src="{{asset("vendor/datatables-plugins/buttons/js/dataTables.buttons.min.js")}}"></script>
    <script src="{{asset("vendor/datatables-plugins/buttons/js/buttons.bootstrap4.min.js")}}"></script>
    <script src="{{asset("vendor/datatables-plugins/jszip/jszip.min.js")}}"></script>
    <script src="{{asset("vendor/datatables-plugins/pdfmake/pdfmake.min.js")}}"></script>
    <script src="{{asset("vendor/datatables-plugins/pdfmake/vfs_fonts.js")}}"></script>
    <script src="{{asset("vendor/datatables-plugins/buttons/js/buttons.html5.min.js")}}"></script>
    <script src="{{asset("vendor/datatables-plugins/buttons/js/buttons.print.min.js")}}"></script>
    <script src="{{asset("vendor/datatables-plugins/buttons/js/buttons.colVis.min.js")}}"></script>
    <script src="{{asset("bs-custom-file-input/bs-custom-file-input.min.js")}}"></script>
    <script>
        $(function () {
            $('#example1').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "responsive": false,
            });
        });
    </script>
@stop